---
abstract: 'Alien module for ta-lib from http://ta-lib.org'
author:
  - 'Vikas N. Kumar <vikas@cpan.org>'
build_requires:
  Archive::Tar: 0
  Archive::Zip: 0
  Cwd: 0
  ExtUtils::CBuilder: 0
  File::HomeDir: 0
  File::Path: 0
  File::Spec: 0
  File::Which: 0
  LWP::Simple: 0
  Module::Build: 0
  Test::More: 0
configure_requires:
  Archive::Tar: 0
  Archive::Zip: 0
  Cwd: 0
  File::HomeDir: 0
  File::Path: 0
  File::Spec: 0
  File::Which: 0
  LWP::Simple: 0
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4207, CPAN::Meta::Converter version 2.132661'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Alien-TALib
provides:
  Alien::TALib:
    file: lib/Alien/TALib.pm
    version: 0.07
requires:
  Archive::Tar: 0
  Archive::Zip: 0
  Cwd: 0
  File::HomeDir: 0
  File::Spec: 0
  File::Which: 0
  LWP::Simple: 0
resources:
  bugtracker: https://github.com/vikasnkumar/Alien-TALib/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/vikasnkumar/Alien-TALib
version: 0.07
